version: '3.8'

services:
  # Flask API service
  flask:
    build:
      context: ./flask
      dockerfile: dockerfile
    container_name: flask-app
    ports:
      - "5500:5500"
    environment:
      DB_NAME: movies_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # PostgreSQL service
  db:
    image: postgres:16
    container_name: movie-db
    environment:
      POSTGRES_DB: movies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movies_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # Nginx service (for serving frontend and reverse proxy)
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/reactApp/src:/app
    depends_on:
      flask:
        condition: service_started
    restart: always

volumes:
  pgdata: