name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Launch EC2 Instance (if not running)
        run: |
          INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query "Reservations[0].Instances[0].State.Name" --output text)
          if [ "$INSTANCE_STATE" != "running" ]; then
            echo "Starting EC2 instance..."
            aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
            aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
          else
            echo "EC2 instance is already running."
          fi

      - name: Deploy App to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user  
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update packages and install Docker if not installed
            sudo apt update -y && sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER

            # Pull Docker images
            docker pull ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest

            # Stop existing containers (if running)
            docker stop flask-backend || true
            docker stop react-frontend || true
            docker rm flask-backend || true
            docker rm react-frontend || true

            # Run Flask Backend
            docker run -d -p 5500:5500 --name flask-backend ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest

            # Run React Frontend (Served via Nginx)
            docker run -d -p 80:80 --name react-frontend ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest

            echo "Deployment Successful!"

