name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug - List Repository Files
      run: ls -la
    



    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


    - name: Pull Docker image from Docker Hub
      run: docker pull jeremyhuegel/flask-backend:latest
    
    - name: Pull Docker image from Docker Hub
      run: docker pull jeremyhuegel/nginx-backend:1.0

    - name: Debug
      continue-on-error: true
      run: |
        pwd
        ls -lah
    
  
    - name: copy files to server using SCP 1
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        source: "./templates/flask-react/docker-compose.yml"
        target: "/home/ubuntu/"

    - name: copy files to server using SCP 2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        source: "./templates/flask-react/nginx/Dockerfile"
        target: "/home/ubuntu/nginx/Dockerfile"

    - name: copy files to server using SCP 3
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        source: "./templates/flask-react/nginx/default.conf"
        target: "/home/ubuntu/nginx/default.conf"

    - name: copy files to server using SCP 4
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          source: "./templates/flask-react/flask/Dockerfile"
          target: "/home/ubuntu/flask/Dockerfile"



    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          
        
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx-backend:1.0
 
          
          docker-compose up -d
          
        
# docker stop jeremyhuegel/flask-backend:latest
# docker stop jeremyhuegel/nginx-backend:1.0

# docker rm jeremyhuegel/flask-backend:latest
# docker rm jeremyhuegel/nginx-backend:1.0

# docker run -d -p 5500:5500 --name flask-backend --restart always ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend:latest
# docker run -d -p 80:80 --name nginx-backend --restart always --link flask-backend ${{ secrets.DOCKERHUB_USERNAME }}/nginx-backend:1.0

#docker-compose down
#docker-compose up -d

