name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug - List Repository Files
      run: ls -la
    

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jeremyhuegel/flask-backend .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/jeremyhuegel/flask-backend

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          docker stop flask-react-container || true
          docker rm flask-react-container || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-react-app
          docker run -d -p 80:80 --name flask-react-container --restart always ${{ secrets.DOCKERHUB_USERNAME }}/flask-react-app



#declare docker build and push

#declare remote state terraform
#dynamodb - jeremytable-assignment3 / partion key: ID
#s3 bucket  manually* - jeremybucket-assignment3