name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug - List Repository Files
      run: ls -la
    



    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


    - name: Pull Docker image from Docker Hub
      run: docker pull jeremyhuegel/flask-backend:1.0
    
    - name: Pull Docker image from Docker Hub
      run: docker pull jeremyhuegel/nginx-backend:1.0

    - name: Run Docker Container
      run: docker run -d -p 5500:5500 --name flask-backend --restart always jeremyhuegel/flask-backend:1.0
    
    - name: Run Docker Container
      run: docker run -d -p 80:80 --name nginx-backend --restart always --link flask-backend jeremyhuegel/nginx-backend:1.0
    
    # - name: Build and push Docker image
    #   run: |
    #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend ./jeremyhuegel
    #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend
      
    # - name: Build and push Docker image
    #   run: |
    #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-backend ./jeremyhuegel
    #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-backend

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend:1.0
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx-backend:1.0

          docker run -d -p 5500:5500 --name flask-backend --restart always ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend
          docker run -d -p 80:80 --name nginx-backend --restart always --link flask-backend ${{ secrets.DOCKERHUB_USERNAME }}/nginx-backend


  #Log into EC2 First
  #w/ docker login script
  #Pull images
